set nocompatible
:set mouse=a
set number
set expandtab
set tabstop=4
set shiftwidth=4
filetype plugin indent on
syntax on
runtime! config/**/*.vim
set backspace=indent,eol,start
map Y "+y

call plug#begin('~/.vim/plugged')
" Fuzzy find
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
" VS Code theme
Plug 'tomasiser/vim-code-dark'
Plug 'scrooloose/nerdtree'
" Git plugin
Plug 'tpope/vim-fugitive'
"Github
Plug 'tpope/vim-rhubarb'
"Main golang plugin
Plug 'fatih/vim-go'
Plug 'Valloric/YouCompleteMe'
" Main markdown plugin
Plug 'plasticboy/vim-markdown'
" create tables in markdown
Plug 'godlygeek/tabular'
call plug#end()

colorscheme codedark

" You complete me
let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'

" Nerd tree
" opens the nerdtree in the correct spot
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
map <C-t> :NERDTreeToggle<CR>
map t :NERDTreeFind<CR>

" Json
command Json %!python -m json.tool

" Golang
let g:go_fmt_command = "goimports"
let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['vet', 'golint']
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
let g:go_list_type = "quickfix"

" Makefiles
autocmd FileType make set noexpandtab shiftwidth=8 softtabstop=0

" Markdown
let g:vim_markdown_folding_disabled = 1

" Several windows
map <C-l> <C-w>l
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k

" fzf Search in project
map ; :Files<CR>
map m :Rg<CR>
map <C-e> :History<CR>
" automatically save files before switching buffers
:set hidden
:set autowriteall

" Python
autocmd Filetype python setlocal expandtab tabstop=4 shiftwidth=4
let g:black_linelength = 120
